export const GET_PRODUCTS = "GET_PRODUCTS"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL"
export const ADD_TO_CART = "ADD_TO_CART"
export const DELETE_FROM_CART = "DELETE_FROM_CART"
export const FILTER_BY_PRICE = "FILTER_BY_PRICE"

export const GET_USERS = "GET_USERS"
export const CREATE_USER = "CREATE_USER"

export const GET_CATEGORIES = "GET_CATEGORIES"
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY"
export const FILTER_BY_SUBCATEGORY = "FILTER_BY_SUBCATEGORY"
